### ISSUE TITLE
TV app erroring out by the volume mute function and status of the TV is wrong

### ISSUE THREAD

**Issue by James712346** [AntonioMeireles/homebridge-vieramatic#10]
After updating my plugin from 0.5.8 to the lastest (0.5.87), I would sometime receive this error when I start up homebridge, but the status of the TV is wrong and when I try to turn it on the accessory would become unresponsive
```
[2/17/2020, 10:02:51 AM] [PanasonicVieraTV] found a Panasonic VIErA TV (S610) at 192.168.86.28 .

[2/17/2020, 10:02:51 AM] [PanasonicVieraTV] DidFinishLaunching
[2/17/2020, 10:02:51 AM] prince is running on port 52107.
[2/17/2020, 10:02:51 AM] Please add [prince] manually in Home app. Setup Code: 031-45-154
[2/17/2020, 10:02:52 AM] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
[2/17/2020, 10:03:01 AM] [orbit] Unhandled message received: low_battery
[2/17/2020, 10:03:03 AM] [Living Room] Failed to pair! Make sure TV is online and you click "Allow" on the popup
[2/17/2020, 10:03:03 AM] [orbit] Unhandled message received: low_battery
[2/17/2020, 10:03:16 AM] [Google Smart Home] Finished instance discovery
[2/17/2020, 10:03:31 AM] [Google Smart Home] Sending Sync Request
(node:396) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at Vieramatic.getMute (/homebridge/node_modules/homebridge-vieramatic/lib/homebridge.coffee:332:5)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

(node:396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:396) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:396) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at Vieramatic.getMute (/homebridge/node_modules/homebridge-vieramatic/lib/homebridge.coffee:332:5)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

(node:396) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
```

Just to note the TV cannot control the TV volume as its run by a separate unit.

TV model: TH-40CS610A
OS: Alpine Linux (3.11.2)
Docker image: oznu/homebridge

**Comment by James712346** [comment]
I just tried again and found that when the TV is on the accessory would tell me that the TV is off but when I try and turn it on, the TV would turn off. This was the case when turning the TV back on where the accessory would show that its on for 2 seconds then turn off again (though the plugin does successful turn on the TV)
I've just realised that it is very similar to #8 problem but I will keep this issue open for the volume error

**Comment by James712346** [comment]
I just tried again and found that when the TV is on the accessory would tell me that the TV is off but when I try and turn it on, the TV would turn off. This was the case when turning the TV back on where the accessory would show that its on for 2 seconds then turn off again (though the plugin does successful turn on the TV)

**Comment by AntonioMeireles** [comment]
Hi @James712346 

thanks for reporting ! some questions : 

- what do you mean by `the TV cannot control the TV volume as its run by a separate unit` ? could you be please more precise if possible. 
- can you please restart homebridge with debug enabled (`DEBUG=* homebridge ...`) to capture the context of the breakage and paste it here ?
- how are you consuming the plugin ? plain homebridge ? oobs ? over what OS (and version) ? what hw ? and what homebridge and node versions ?

thanks again!

**Comment by AntonioMeireles** [comment]
> I just tried again and found that when the TV is on the accessory would tell me that the TV is off, but when I try and turn it on, the TV would turn off. This was the case when turning the TV back on where the accessory would show that its on for 2 seconds then turn off again (though the plugin does successful turn on the TV)
> I've just realised that it is very similar to #8 problem, but I will keep this issue open for the volume error
> also I did `viera-pair` which was successful for me

ok. regarding this one - so, is this a general issue or only happens if you start plugin with TV off ?

**Comment by koupus** [comment]
Hello Antonio,
same thing here but it happen sometimes without prior action or consequence after...

the log:
(node:60049) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at Vieramatic.getMute (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:346:5)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:60049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14540)
(node:60049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:60049) UnhandledPromiseRejectionWarning: TypeError: undefined is not a function
    at Vieramatic.getMute (/usr/local/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:346:5)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

(node:60049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14541)

**Comment by AntonioMeireles** [comment]
humm.... @koupus 

could you please provide **full** log (i.e. whatever is before this happening)?.

Looking into it (unable to reproduce **yet**)

thanks in advance and a great weekend!

**Comment by koupus** [comment]
@AntonioMeireles  just see it happen when I display the accessories view of the home bridge config UI X...  nothing related at the home app or tv operation!
No disagreement on my side

**Comment by AntonioMeireles** [comment]
@koupus 

**THANKS** - all i wanted was a simple reproducer and you gave me one! (`homebridge-config-ui-x`)

Fix will be out soonish!

**Comment by AntonioMeireles** [comment]
@koupus, @James712346 

just pushed `homebridge-vieramatic@0.5.89`. **if** i got things right the `getMute` errors are now gone. Please confirm.

thanks again for your patience and have a great weekend

**Comment by koupus** [comment]
@AntonioMeireles Ok for me now !

Thanks Antonio

**Comment by AntonioMeireles** [comment]
closing, as this seems to be really fixed. please reopen if issue ressurrects.
